name_or_path: aisingapore/sealion7b
output_dir: /sealion/examples/fine_tuning/models_adepter_7B
run_name: example_fine_tuning_ist

num_train_epochs: 4
num_gpus: 4
seed: 42

log_with: mlflow
log_freq: 1
logging_steps: 30
save_steps: 5000

streaming: False
shuffle_buffer: 4000
size_valid_set: 20
split: "train"

peft:
  lora_alpha: 512
  lora_r: 256
  lora_dropout: 0.05
  target_modules: ["down_proj", "out_proj", "up_proj", "Wqkv"]

seq_length: 2048
attn_impl: triton

lr_scheduler_type: cosine
learning_rate: 3e-4
num_warmup_steps: 100
weight_decay: 0.01
optimizer_type: paged_adamw_32bit
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
gradient_accumulation_steps: 5
gradient_checkpointing: True
